import Head from 'next/head'
import {Title} from '~/components/Title'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-[800svh] bg-neutral-950 overflow-x-hidden">
        <section className="h-[100svh] tw-bg-mesh-gradient-1 flex items-end w-full">
          <Title>hello</Title>
        </section>
      </div>
    </>
  )
}
